### ISSUE TITLE
[EPIC] Load testing

### ISSUE THREAD

**Issue by alexfigtree** [digitalcredentials/dcc-admin-dashboard#40]
- [x]  https://github.com/digitalcredentials/admin-dashboard/issues/41
- [x] Load tests
- [x] https://github.com/digitalcredentials/admin-dashboard/issues/42
- [x] https://github.com/digitalcredentials/transaction-service/issues/10

**Comment by alexfigtree** [comment]
Meeting on 6/24/24 with Jackson and James shows updated documentation for load tests on AWS Lambda here: https://github.com/digitalcredentials/dcc-server-tester/blob/main/README.md

**Comment by alexfigtree** [comment]
Complete, closing
